name: "Branch name mappings utility"
description: "Create branch name mappings by corresponding environment branch"
author: "AlexRogalskiy"

inputs:
  github-ref:
    description: "github reference to parse current branch from"
    required: true
  map:
    description: "collection of branch name mappings"
    required: false
    default: null

outputs:
  environment:
    description: "environment branch name by provided collection of mappings"

runs:
  using: "node12"
  main: "dist/index.js"

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: "battery"
  color: "orange"
