name: "Branch name mappings"
description: "Create branch name by corresponding collection of environment branch name mappings"
author: "AlexRogalskiy"

inputs:
  github-ref:
    description: "github reference to parse the current branch from"
    required: true
  map:
    description: "collection of branch name mappings"
    required: false
    default: 'null'

outputs:
  environment:
    description: "environment branch name by provided collection of name mappings"

runs:
  using: "node12"
  main: "dist/index.js"

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: "battery"
  color: "orange"
